FROM node:22-alpine

WORKDIR /usr/src/app

# Instalar dependencias
COPY app/api/package*.json ./
RUN npm install -g npm@11.0.0

# Copiar código fuente
COPY app/api .

# Crear directorio para logs
RUN mkdir -p /var/log/techwave
VOLUME /var/log/techwave

EXPOSE 3000

CMD ["node", "server.js"]


