FROM nginx:alpine

# Copiar configuración de nginx
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivos web
COPY app/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]